# [Declare]

# [Level 0]
# UMS-By-C/head/define.h 
define_h : define.h


#[Level 1]
define_h . SCN(Sniffer code number)

#[Level 2]
define_h . SCN(Sniffer code number) . ERROR
define_h . SCN(Sniffer code number) . BUG
define_h . SCN(Sniffer code number) . EXCEPTION

#[Level 3]
define_h . SCN(Sniffer code number) . ERROR . SOCKET
define_h . SCN(Sniffer code number) . ERROR . BIND
define_h . SCN(Sniffer code number) . ERROR . ACCEPT
