이상한 오류, 버그, 예외 발생 -> Sniffer code: Sniffer code number 전달

ERROR <-> Sniffer code

Sniffer code -> 종료

define_h -> Sniffer code
define_h -> ERROR

define_h.SNC(Sniffer code).ERROR
define_h.SNC(Sniffer code).BUG
define_h.SNC(Sniffer code).EXCEPTION
define_h.SNC(Sniffer code).ERROR.~~
define_h.SNC(Sniffer code).BUG.~~
define_h.SNC(Sniffer code).EXCEPTION.~~

explanation: |md    
  # 에러, 오류, 버그

  에러는 응용 프로그램의 사용자에 의해서 발생한다.
  -
  버그는 프로그래머에 의한 에러이다.
  -
  예외는 예방하기가 어렵거나 불가능한 것들이다.
  -





|
