# [Declare]

# [Level 0]
# UMS-By-C/head/untils.h
untils_h : untils.h


#[Level 1]
untils_h . sniffer_code

#[Level 2]
untils_h . sniffer_code . sniffer_code_c

#[Level 3]
untils_h . sniffer_code . sniffer_code_c . function_sniffed

#[Level 4]

